### ISSUE TITLE
Keep dependencies up to date.

### ISSUE THREAD

**Issue by brodycritchlow** [tylercritchlow/Social-media-platform#13]
I found a github bot that will automatically do this for us. [Invite Here](https://github.com/apps/renovate/installations/new/permissions?target_id=24994624). We should add this to save ourselves from security vulnerabilities in deprecated / older modules.

**Comment by tylercritchlow** [comment]
Link is bad

**Comment by brodycritchlow** [comment]
Here is updated one: https://github.com/apps/renovate
@tylercritchlow
